# Generated by Django 5.2.6 on 2025-09-15 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('footwear', 'Footwear'), ('scarf', 'Scarf'), ('jacket', 'Jacket'), ('hat', 'Hat'), ('accessories', 'Accessories')], default='accessories', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
