# Generated by Django 5.2.6 on 2025-10-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_discount',
        ),
    ]
